version: "3.1"

volumes:
  pg_eturn:
  rabbitmq_eturn:

services:
  eturn_db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pg_eturn:/var/lib/postgresql/data
    ports:
      - "37113:5432"
  rabbitmq:
    image: rabbitmq:3.10.7-management
    env_file:
      - .env
    volumes:
      - rabbitmq_eturn:/var/lib/rabbitmq
    ports:
      - "37122:5672"
      - "37112:15672"
  eturn_app:
    restart: always
    build: .
    ports:
      - "37111:37111"
    depends_on:
      - eturn_db
      - rabbitmq
    env_file:
      - .env

