version: "3.1"

volumes:
  pg_eturn:

services:
  eturn_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=eturn_user
      - POSTGRES_PASSWORD=DfcbkmtdCfvjdfhjd
      - POSTGRES_DB=eturn
    volumes:
      - pg_eturn:/var/lib/postgresql/data
    ports:
      - "37113:5432"
  rabbitmq:
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "37122:5672"
      - "37112:15672"
  eturn_app:
    restart: always
    build: .
    ports:
      - "37111:37111"
    depends_on:
      - eturn_db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://eturn_db:5432/eturn"
      SPRING_DATASOURCE_USERNAME: eturn_user
      SPRING_DATASOURCE_PASSWORD: DfcbkmtdCfvjdfhjd
      ETURN_DEFAULTS_USERNAME: adminEturnQFNJLe2FQw345
      ETURN_DEFAULTS_PASSWORD: JFIOASF__1**FQ3!$4F
      TOKEN_SIGNING_KEY: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 37122
      RABBITMQ_VHOST: /
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest