spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    url: env
    username: env
    password: env

  rabbitmq:
    host: rabbitmq
    port: 37122
    username: env
    password: env
    virtual-host: /
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: none
      ddl-auto: update
#      ddl-auto: create-drop
    generate-ddl: true

server:
  port: 37111
  servlet:
    context-path: /eturn/api

token:
  signing:
    key: env

eturn:
  defaults:
    username: env
    password: env
  rabbitmq:
    queue: env
    topic: env
    exchange: env

springdoc:
  swagger-ui:
    default-model-expand-depth: -1
    disable-swagger-default-url: true


external:
  api:
    url: "https://lk.etu.ru/api/profile/0"