spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    url: env
    username: env
    password: env

  rabbitmq:
    host: rabbitmq
    port: 37122
    username: env
    password: env
    virtual-host: /
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: none
      ddl-auto: update
     # ddl-auto: create-drop
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true                       # Включение Flyway
    schemas: public                     # Схема для таблицы `flyway_schema_history`
    sql-migration-suffixes: .sql        # Суффикс для SQL-файлов
    encoding: UTF-8                     # Кодировка файлов миграций
    validate-on-migrate: true           # Проверять контрольные суммы миграций
    create-schemas: true                # Автоматически создавать схему, если её нет
    out-of-order: false                 # Запретить выполнение миграций не по порядку

server:
  port: 37111
  servlet:
    context-path: /eturn/api

token:
  signing:
    key: env

eturn:
  etu:
    secret: env
    client: env

  defaults:
    username: env
    password: env
  rabbitmq:
    queue: env
    topic: env
    exchange: env

springdoc:
  swagger-ui:
    default-model-expand-depth: -1
    disable-swagger-default-url: true


external:
  api:
    url: "https://lk.etu.ru/id/profile"
    url_etu_id: "https://id.etu.ru/oauth/token"
    url_profile: "https://id.etu.ru/api/profile"
    url_mobile: "https://lk.etu.ru/api/profile/0"