spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
#    username: v.snigirev
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

server:
  port: 8089

#spring.datasource.url=jdbc:postgresql://185.154.194.3:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=0000
#spring.jpa.generate-ddl=true
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#log4j.rootLogger=INFO
#log4j.logger.org.hibernate.type.descriptor.sql=TRACE

#hostname=localhost:8080

