spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
#    url: jdbc:postgresql://localhost:5432/eturn
#    username: postgres
#    password: postgres

#    url: jdbc:postgresql://localhost:5432/postgres
#    username: vsnigerev
#    password: 12345678
#    password: 0000
    #url: jdbc:postgresql://127.0.0.1:5432/postgres
    #username: ${POSTGRES_USERNAME:postgresql}
    #password: ${POSTGRES_PASSWORD:12345678}
      url: jdbc:postgresql://127.0.0.1:5432/eturn
      username: ${POSTGRES_USERNAME:developer}
      password: ${POSTGRES_PASSWORD:dfcbkmtd2004}
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: none
      ddl-auto: create-drop
    generate-ddl: true

server:
  port: 8089

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855


springdoc:
#  api-docs:
#    path: "http://eturn.ru/api/v3/api-docs"
  swagger-ui:
    default-model-expand-depth: -1
    disable-swagger-default-url: true


external:
  api:
    url: "https://lk.etu.ru/api/profile/0"