spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:37113/eturn
    username: admin
    password: admin

  rabbitmq:
    host: rabbitmq
    port: 37122
    username: eturnuser
    password: klbWQFEfeGr4vdv41fs
    virtual-host: /
#    template:
#      exchange: response.exchange
#      routing-key: response.routing.key

#    url: jdbc:postgresql://localhost:5432/postgres
#    username: vsnigerev
#    password: 12345678
#    password: 0000
    #url: jdbc:postgresql://127.0.0.1:5432/postgres
    #username: ${POSTGRES_USERNAME:postgresql}
    #password: ${POSTGRES_PASSWORD:12345678}
#      url: jdbc:postgresql://127.0.0.1:5432/eturn
#      username: ${POSTGRES_USERNAME:developer}
#      password: ${POSTGRES_PASSWORD:dfcbkmtd2004}
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: none
      ddl-auto: create-drop
    generate-ddl: true

server:
  port: 37111

token:
  signing:
    key: admin

eturn:
  defaults:
    username: "admin"
    password: "admin"
  rabbitmq:
    queue: "eturn-queue"
    topic: "eturn-notifications"
    exchange: "eturn-qkjib2rtq3"

springdoc:
#  api-docs:
#    path: "http://eturn.ru/api/v3/api-docs"
  swagger-ui:
    default-model-expand-depth: -1
    disable-swagger-default-url: true


external:
  api:
    url: "https://lk.etu.ru/api/profile/0"