CREATE TABLE counter
(
    id    VARCHAR(255) NOT NULL,
    value INTEGER,
    CONSTRAINT pk_counter PRIMARY KEY (id)
);

CREATE TABLE faculty
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_faculty PRIMARY KEY (id)
);

CREATE TABLE feedback
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    text       VARCHAR(255),
    evaluation INTEGER,
    date       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_feedback PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number     VARCHAR(255),
    course     INTEGER,
    faculty_id BIGINT,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE member
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id               BIGINT,
    turn_id               BIGINT,
    access_member         VARCHAR(255),
    invited_for_moderator BOOLEAN NOT NULL,
    invited_for_turn      VARCHAR(255),
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE TABLE notify
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type    VARCHAR(255),
    created TIMESTAMP WITHOUT TIME ZONE,
    user_id BIGINT,
    is_many BOOLEAN NOT NULL,
    CONSTRAINT pk_notify PRIMARY KEY (id)
);

CREATE TABLE positions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT NOT NULL,
    turn_id    BIGINT NOT NULL,
    member_id  BIGINT,
    group_name VARCHAR(255),
    start      BOOLEAN,
    date_end   TIMESTAMP WITHOUT TIME ZONE,
    date_start TIMESTAMP WITHOUT TIME ZONE,
    skip_count INTEGER,
    CONSTRAINT pk_positions PRIMARY KEY (id)
);

CREATE TABLE turn
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hash                 VARCHAR(255),
    name                 VARCHAR(255),
    description          VARCHAR(255),
    user_id              BIGINT,
    turn_type            VARCHAR(255),
    access_turn_type     VARCHAR(255),
    date_start           TIMESTAMP WITHOUT TIME ZONE,
    date_end             TIMESTAMP WITHOUT TIME ZONE,
    timer                INTEGER,
    position_count       INTEGER,
    tags                 VARCHAR(255),
    access_tags          VARCHAR(255),
    extension_times      INTEGER,
    smoothed_value       DOUBLE PRECISION,
    total_time           BIGINT,
    average_time         INTEGER,
    count_positions_left INTEGER,
    CONSTRAINT pk_turn PRIMARY KEY (id)
);

CREATE TABLE turn_faculty
(
    faculty_id BIGINT NOT NULL,
    turn_id    BIGINT NOT NULL,
    CONSTRAINT pk_turn_faculty PRIMARY KEY (faculty_id, turn_id)
);

CREATE TABLE turn_group
(
    group_id BIGINT NOT NULL,
    turn_id  BIGINT NOT NULL,
    CONSTRAINT pk_turn_group PRIMARY KEY (group_id, turn_id)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login              VARCHAR(255),
    password           VARCHAR(255),
    name               VARCHAR(255),
    group_id           BIGINT,
    role               VARCHAR(255),
    token_notification VARCHAR(255),
    application_type   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE UNIQUE INDEX group_number_index ON groups (number);

CREATE UNIQUE INDEX hash_index ON turn (hash);

CREATE UNIQUE INDEX login_index ON users (login);

ALTER TABLE feedback
    ADD CONSTRAINT FK_FEEDBACK_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_FACULTY FOREIGN KEY (faculty_id) REFERENCES faculty (id);

ALTER TABLE member
    ADD CONSTRAINT FK_MEMBER_ON_TURN FOREIGN KEY (turn_id) REFERENCES turn (id);

ALTER TABLE member
    ADD CONSTRAINT FK_MEMBER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE positions
    ADD CONSTRAINT FK_POSITIONS_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE positions
    ADD CONSTRAINT FK_POSITIONS_ON_TURN FOREIGN KEY (turn_id) REFERENCES turn (id);

ALTER TABLE positions
    ADD CONSTRAINT FK_POSITIONS_ON_TURNZJjfpn FOREIGN KEY (turn_id) REFERENCES users (id);

ALTER TABLE positions
    ADD CONSTRAINT FK_POSITIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE turn
    ADD CONSTRAINT FK_TURN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE turn_faculty
    ADD CONSTRAINT fk_turfac_on_faculty FOREIGN KEY (faculty_id) REFERENCES faculty (id);

ALTER TABLE turn_faculty
    ADD CONSTRAINT fk_turfac_on_turn FOREIGN KEY (turn_id) REFERENCES turn (id);

ALTER TABLE turn_group
    ADD CONSTRAINT fk_turgro_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE turn_group
    ADD CONSTRAINT fk_turgro_on_turn FOREIGN KEY (turn_id) REFERENCES turn (id);