name: Deploy Spring App

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.USERNAME}}@${{secrets.SERVER_IP}} << 'EOF'
            cd ~/eturn-back

            # Останавливаем и удаляем старый контейнер приложения, не трогая БД и RabbitMQ
            docker compose stop eturn_app
            docker compose rm -f eturn_app

            # Забираем последнюю версию кода
            git pull origin prod
          
            # Обновляем .env файл из GitHub Secrets
            echo "${{ secrets.ENV_FILE }}" > .env
            cat .env
            ls -la

            # Удаляем ненужные образы и кеши
            docker system prune -af
          
            # Собираем и запускаем новый контейнер приложения
            
          EOF
